# -------------------------------------------------------------------------------------------------
# IF - ELIF - ELSE
# -------------------------------------------------------------------------------------------------

print('\n\t\tIF - ELIF - ELSE\n')

age = 16                                                # first example					
                                                        # ...
if age < 18:                                            # ...
    print("No beer for you!\n")                         # ...

name = "Lucy"                                           # second example
                                                        # ...
if name is "Captain":                                   # ...
    print("Hey there Captain")                          # ...
elif name is "Lucy":                                    # ...
    print("Hey there Lucy")                             # ...
elif name is "Andrew":                                  # ...
    print("Hey there Andrew")                           # ...
else:                                                   # ...
    print("Your name is not registered yet!")           # ...
