#FOR LOOP

print('\n\t\tFOR LOOP\t\t\n')


foods = ["Bacon" , "Tuna" , "Ham" , "Sausages" , "Beef"]		# first example
																# ...
for i in foods:													# ...
	print(i)  													# ...
	print("Len is:", len(i))									# ...

print ('')

foods = ["Bacon" , "Tuna" , "Ham" , "Sausages" , "Beef"]		# second example
																# ...
for i in foods[:2]:												# ...
	print(i)  													# ...

print('')
